
@controller= https://localhost:5001/api/pembelian

POST {{controller}}/CreateOrder HTTP/1.1
Content-Type: application/json

{
    "idorder":null,
    "idmanajemen":1,
    "idpembeli":2,
    "tgl_order":"2020-2-17",
    "wkt_exp_order":"2020-2-17",
    "alamatpengiriman":"Diamna Saja"
}
####
GET {{controller}}/GetOrderByIdPembeli/2 HTTP/1.1
Content-Type: application/json





